name: my-sql-check
on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    name: Building stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.0"

      - name: Create and initialize .env file
        run: |
          echo "ENV=local
          DB_HOST=localhost
          DB_PORT=3306
          DB_NAME=test_db
          DB_USER=root
          DB_PASS=root"> .env

      - name: Setup MySQL Database
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE test_db;' -uroot -proot
      
      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3800 # Optional, default value is 3306. The port of host
          container port: 3307 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'some_test' # Optional, default value is "test". The specified database which will be create
          mysql root password: 'root' # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: 'root' # R    



#       - name: Setup MySQL Database
#         run: |
#           sudo /etc/init.d/mysql start
#           mysql -e 'CREATE DATABASE test_db;' -uroot -proot

