name: test
on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root
    name: Building test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.0"

      - name: Create and initialize .env file
        run: |
          echo "ENV=local
          DB_HOST=localhost
          DB_PORT=3306
          DB_NAME=test_db
          STORAGE_BUCKET_NAME=${{ secrets.STORAGE_BUCKET_NAME_DEV }}
          DB_USER=root
          DB_PASS=root"> .env\
          
       
      - name: Set up MySQL
        run: |
          sudo /usr/bin/mysqld start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

          
#       - run: |
#           sudo find / -name mysqld 
#       - name: Setup MySQL Database
#         run: |
#           sudo /usr/libexec/mysqld start 
#           mysql -e 'CREATE DATABASE test_db;' -uroot -proot





