name: test
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Building test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.0"

      - name: Create and initialize .env file
        run: |
          echo "ENV=local
          DB_HOST=localhost
          DB_PORT=3306
          DB_NAME=test_db
          STORAGE_BUCKET_NAME=${{ secrets.STORAGE_BUCKET_NAME_DEV }}
          DB_USER=root
          DB_PASS=root"> .env
      - run: |
          sudo find / -name mysqld 
      - name: Setup MySQL Database
        run: |
          sudo /usr/libexec/mysqld start 
          mysql -e 'CREATE DATABASE test_db;' -uroot -proot





