name: test
on:
  push:
    branches:
      - master

jobs:
  setup-mysql: 
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      mydb:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
    - name: Verify MySQL connection from container 
      run: |
        apt-get update
        apt-get install -y mysql-client
        mysql --host mydb -uroot -ppassword -e "SHOW DATABASES"

        
  build:
    needs:  setup-mysql
    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root
    name: Building test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.0"

      - name: Create and initialize .env file
        run: |
          echo "ENV=local
          DB_HOST=localhost
          DB_PORT=3306
          DB_NAME=test_db
          STORAGE_BUCKET_NAME=${{ secrets.STORAGE_BUCKET_NAME_DEV }}
          DB_USER=root
          DB_PASS=root"> .env\
      - name: Check docker username and password
        run: |
          echo "DOCKER_USER = \"${{secrets.DOCKER_USERNAME}}\"
          \nDOCKER_USER = \"${{secrets.DOCKER_PASSWORD}}\"
            "
  

          
#       - run: |
#           sudo find / -name mysqld 
#       - name: Setup MySQL Database
#         run: |
#           sudo /usr/libexec/mysqld start 
#           mysql -e 'CREATE DATABASE test_db;' -uroot -proot





