name: my-sql-check
on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    name: Building stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.0"

      - name: Create and initialize .env file
        run: |
          echo "ENV=local
          DB_HOST=localhost
          DB_PORT=3306
          DB_NAME=test_db
          DB_USER=root
          DB_PASS=root"> .env
          

      - run: |
         cp support-files/mysql.server /etc/init.d/mysql.server

      - name: Setup MySQL Database
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE test_db;' -uroot -proot
          

#       - name: Setup MySQL Database
#         run: |
#           sudo /etc/init.d/mysql start
#           mysql -e 'CREATE DATABASE test_db;' -uroot -proot

